#!/usr/bin/env python3
"""
bench_report.py — runs the evaluation benchmarks head-less and prints a
report-ready Markdown table (CPU share vs priority, and LLM-cache hit-rate).

It only RUNS existing benchmark programs (cfs_share, eval); it changes no kernel
code. Boots an isolated xv6/qemu (smp=1 so a multi-core host does not trivially
absorb every runnable child, which is required for a meaningful CFS share
measurement) via tools/qemu_harness.py, on a dedicated port + private fs.img copy.

    python3 tools/bench_report.py            # print Markdown to stdout
    python3 tools/bench_report.py > docs/BENCHMARKS.md

Build first:  (cd xv6-riscv && make kernel/kernel fs.img)
Needs ~150 MB free host RAM (qemu runs with -m 128M); on a tight machine,
close other memory hogs first or the guest may fail to finish booting.
"""
import os, sys, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qemu_harness import QemuHarness

FS_COPY = "/tmp/fs_bench.img"
LOG     = "/tmp/bench_qemu.log"
PORT    = 5558

# Priority sweep for the CFS share table (formerly hard-coded in cfs_bench.c).
SWEEP_PRIOS = [0, 4, 8, 12, 16, 19]
SWEEP_TICKS = 150

# Linux sched_prio_to_weight, as ported in kernel/proc.c cfs_weight[] (index =
# priority+20). Used only to show the *expected* share beside the measured one.
WEIGHT = {0: 1024, 4: 423, 8: 172, 12: 70, 16: 29, 19: 15}

def info(msg): print(f"[bench] {msg}", file=sys.stderr, flush=True)

def run_cfs_share(h):
    base = len(h.transcript())
    h.send("cfs_share %d %s" % (SWEEP_TICKS, " ".join(str(p) for p in SWEEP_PRIOS)))
    if not h.wait_for("CFSBENCH DONE", timeout=60.0):
        info("cfs_share timed out"); return []
    tail = h.transcript()[base:]
    rows = []
    for m in re.finditer(r"CFSBENCH prio=(-?\d+) count=(\d+)", tail):
        rows.append((int(m.group(1)), int(m.group(2))))
    return rows

def run_cache_hitrate(h, n=50):
    base = len(h.transcript())
    h.send(f"eval cache {n}")
    if not h.wait_for("overall", timeout=30.0):
        info("eval cache timed out"); return None
    tail = h.transcript()[base:]
    m = re.search(r"hits (\d+) / total (\d+) \((\d+)%\)", tail)
    return (int(m.group(1)), int(m.group(2)), int(m.group(3))) if m else None

def md_table(rows, cache):
    total = sum(c for _, c in rows) or 1
    out = []
    out.append("## CFS 우선순위 → CPU 점유율 (smp=1)\n")
    out.append("동일 wall-clock 동안 우선순위별 자식이 경쟁한 루프 카운트와 점유율. "
               "낮은 priority 값 = 높은 가중치 = 더 많은 CPU.\n")
    out.append("| priority | 가중치(weight) | loop count | 측정 share | 기대 share |")
    out.append("|---:|---:|---:|---:|---:|")
    rows = sorted(rows, key=lambda r: r[0])
    wsum = sum(WEIGHT.get(p, 0) for p, _ in rows) or 1
    for p, c in rows:
        meas = 100.0 * c / total
        exp = 100.0 * WEIGHT.get(p, 0) / wsum
        out.append(f"| {p} | {WEIGHT.get(p,'?')} | {c:,} | {meas:.1f}% | {exp:.1f}% |")
    out.append(f"\n_total = {total:,} iterations, {len(rows)} priority levels._\n")
    out.append("## LLM 응답 캐시 hit-rate\n")
    if cache:
        hits, tot, pct = cache
        out.append(f"`eval cache`: 2라운드(cold→warm) 동일 키 {tot//2}개 조회 → "
                   f"hits {hits} / total {tot} = **{pct}%**.\n")
    else:
        out.append("_측정 실패._\n")
    return "\n".join(out)

def main():
    with QemuHarness(port=PORT, fs_copy=FS_COPY, log=LOG, tag="bench") as h:
        h.start()
        if not h.wait_boot():
            sys.exit("[bench] shell never came up — see " + LOG)
        info("shell up; running benchmarks (cfs_share ~15s)...")
        rows  = run_cfs_share(h)
        cache = run_cache_hitrate(h, 50)
        print("<!-- generated by tools/bench_report.py (smp=1) -->\n")
        print(md_table(rows, cache))
        sys.exit(0 if rows else 1)

if __name__ == "__main__":
    main()
